[build]
  base    = ""
  publish = "target/site"
  command = "mvn spring-boot:run"
[build.environment]
  MONGODB_URI2 = "mongodb+srv://abhishekkadam007:newtech%402@cluster0.fvdcp.mongodb.net/newTech?retryWrites=true&w=majority"